/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as HealthRouteImport } from './routes/health'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedIngredientsRouteImport } from './routes/_authenticated/ingredients'
import { Route as AuthenticatedPantryRouteImport } from './routes/_authenticated/pantry'
import { Route as AuthenticatedPlannerRouteImport } from './routes/_authenticated/planner'
import { Route as AuthenticatedSpendingRouteImport } from './routes/_authenticated/spending'
import { Route as AuthenticatedStoresRouteImport } from './routes/_authenticated/stores'
import { Route as AuthenticatedSuggestRouteImport } from './routes/_authenticated/suggest'
import { Route as AuthenticatedHouseholdSettingsRouteImport } from './routes/_authenticated/household.settings'
import { Route as AuthenticatedRecipesIndexRouteImport } from './routes/_authenticated/recipes/index'
import { Route as AuthenticatedRecipesBulkImportRouteImport } from './routes/_authenticated/recipes/bulk-import'
import { Route as AuthenticatedRecipesImportRouteImport } from './routes/_authenticated/recipes/import'
import { Route as AuthenticatedRecipesNewRouteImport } from './routes/_authenticated/recipes/new'
import { Route as AuthenticatedShoppingListIndexRouteImport } from './routes/_authenticated/shopping-list/index'
import { Route as AuthenticatedShoppingListListIdRouteImport } from './routes/_authenticated/shopping-list/$listId'
import { Route as AuthenticatedRecipesRecipeIdIndexRouteImport } from './routes/_authenticated/recipes/$recipeId/index'
import { Route as AuthenticatedRecipesRecipeIdEditRouteImport } from './routes/_authenticated/recipes/$recipeId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIngredientsRoute =
  AuthenticatedIngredientsRouteImport.update({
    id: '/ingredients',
    path: '/ingredients',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPantryRoute = AuthenticatedPantryRouteImport.update({
  id: '/pantry',
  path: '/pantry',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlannerRoute = AuthenticatedPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSpendingRoute = AuthenticatedSpendingRouteImport.update({
  id: '/spending',
  path: '/spending',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStoresRoute = AuthenticatedStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSuggestRoute = AuthenticatedSuggestRouteImport.update({
  id: '/suggest',
  path: '/suggest',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHouseholdSettingsRoute =
  AuthenticatedHouseholdSettingsRouteImport.update({
    id: '/household/settings',
    path: '/household/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRecipesIndexRoute =
  AuthenticatedRecipesIndexRouteImport.update({
    id: '/recipes/',
    path: '/recipes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRecipesBulkImportRoute =
  AuthenticatedRecipesBulkImportRouteImport.update({
    id: '/recipes/bulk-import',
    path: '/recipes/bulk-import',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRecipesImportRoute =
  AuthenticatedRecipesImportRouteImport.update({
    id: '/recipes/import',
    path: '/recipes/import',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRecipesNewRoute = AuthenticatedRecipesNewRouteImport.update({
  id: '/recipes/new',
  path: '/recipes/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedShoppingListIndexRoute =
  AuthenticatedShoppingListIndexRouteImport.update({
    id: '/shopping-list/',
    path: '/shopping-list/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedShoppingListListIdRoute =
  AuthenticatedShoppingListListIdRouteImport.update({
    id: '/shopping-list/$listId',
    path: '/shopping-list/$listId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRecipesRecipeIdIndexRoute =
  AuthenticatedRecipesRecipeIdIndexRouteImport.update({
    id: '/recipes/$recipeId/',
    path: '/recipes/$recipeId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRecipesRecipeIdEditRoute =
  AuthenticatedRecipesRecipeIdEditRouteImport.update({
    id: '/recipes/$recipeId/edit',
    path: '/recipes/$recipeId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/app': typeof AuthenticatedAppRoute
  '/ingredients': typeof AuthenticatedIngredientsRoute
  '/pantry': typeof AuthenticatedPantryRoute
  '/planner': typeof AuthenticatedPlannerRoute
  '/spending': typeof AuthenticatedSpendingRoute
  '/stores': typeof AuthenticatedStoresRoute
  '/suggest': typeof AuthenticatedSuggestRoute
  '/household/settings': typeof AuthenticatedHouseholdSettingsRoute
  '/recipes/bulk-import': typeof AuthenticatedRecipesBulkImportRoute
  '/recipes/import': typeof AuthenticatedRecipesImportRoute
  '/recipes/new': typeof AuthenticatedRecipesNewRoute
  '/shopping-list/$listId': typeof AuthenticatedShoppingListListIdRoute
  '/recipes/': typeof AuthenticatedRecipesIndexRoute
  '/shopping-list/': typeof AuthenticatedShoppingListIndexRoute
  '/recipes/$recipeId/edit': typeof AuthenticatedRecipesRecipeIdEditRoute
  '/recipes/$recipeId/': typeof AuthenticatedRecipesRecipeIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/app': typeof AuthenticatedAppRoute
  '/ingredients': typeof AuthenticatedIngredientsRoute
  '/pantry': typeof AuthenticatedPantryRoute
  '/planner': typeof AuthenticatedPlannerRoute
  '/spending': typeof AuthenticatedSpendingRoute
  '/stores': typeof AuthenticatedStoresRoute
  '/suggest': typeof AuthenticatedSuggestRoute
  '/household/settings': typeof AuthenticatedHouseholdSettingsRoute
  '/recipes/bulk-import': typeof AuthenticatedRecipesBulkImportRoute
  '/recipes/import': typeof AuthenticatedRecipesImportRoute
  '/recipes/new': typeof AuthenticatedRecipesNewRoute
  '/shopping-list/$listId': typeof AuthenticatedShoppingListListIdRoute
  '/recipes': typeof AuthenticatedRecipesIndexRoute
  '/shopping-list': typeof AuthenticatedShoppingListIndexRoute
  '/recipes/$recipeId/edit': typeof AuthenticatedRecipesRecipeIdEditRoute
  '/recipes/$recipeId': typeof AuthenticatedRecipesRecipeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/ingredients': typeof AuthenticatedIngredientsRoute
  '/_authenticated/pantry': typeof AuthenticatedPantryRoute
  '/_authenticated/planner': typeof AuthenticatedPlannerRoute
  '/_authenticated/spending': typeof AuthenticatedSpendingRoute
  '/_authenticated/stores': typeof AuthenticatedStoresRoute
  '/_authenticated/suggest': typeof AuthenticatedSuggestRoute
  '/_authenticated/household/settings': typeof AuthenticatedHouseholdSettingsRoute
  '/_authenticated/recipes/bulk-import': typeof AuthenticatedRecipesBulkImportRoute
  '/_authenticated/recipes/import': typeof AuthenticatedRecipesImportRoute
  '/_authenticated/recipes/new': typeof AuthenticatedRecipesNewRoute
  '/_authenticated/shopping-list/$listId': typeof AuthenticatedShoppingListListIdRoute
  '/_authenticated/recipes/': typeof AuthenticatedRecipesIndexRoute
  '/_authenticated/shopping-list/': typeof AuthenticatedShoppingListIndexRoute
  '/_authenticated/recipes/$recipeId/edit': typeof AuthenticatedRecipesRecipeIdEditRoute
  '/_authenticated/recipes/$recipeId/': typeof AuthenticatedRecipesRecipeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/login'
    | '/app'
    | '/ingredients'
    | '/pantry'
    | '/planner'
    | '/spending'
    | '/stores'
    | '/suggest'
    | '/household/settings'
    | '/recipes/bulk-import'
    | '/recipes/import'
    | '/recipes/new'
    | '/shopping-list/$listId'
    | '/recipes/'
    | '/shopping-list/'
    | '/recipes/$recipeId/edit'
    | '/recipes/$recipeId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/login'
    | '/app'
    | '/ingredients'
    | '/pantry'
    | '/planner'
    | '/spending'
    | '/stores'
    | '/suggest'
    | '/household/settings'
    | '/recipes/bulk-import'
    | '/recipes/import'
    | '/recipes/new'
    | '/shopping-list/$listId'
    | '/recipes'
    | '/shopping-list'
    | '/recipes/$recipeId/edit'
    | '/recipes/$recipeId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/health'
    | '/login'
    | '/_authenticated/app'
    | '/_authenticated/ingredients'
    | '/_authenticated/pantry'
    | '/_authenticated/planner'
    | '/_authenticated/spending'
    | '/_authenticated/stores'
    | '/_authenticated/suggest'
    | '/_authenticated/household/settings'
    | '/_authenticated/recipes/bulk-import'
    | '/_authenticated/recipes/import'
    | '/_authenticated/recipes/new'
    | '/_authenticated/shopping-list/$listId'
    | '/_authenticated/recipes/'
    | '/_authenticated/shopping-list/'
    | '/_authenticated/recipes/$recipeId/edit'
    | '/_authenticated/recipes/$recipeId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  HealthRoute: typeof HealthRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ingredients': {
      id: '/_authenticated/ingredients'
      path: '/ingredients'
      fullPath: '/ingredients'
      preLoaderRoute: typeof AuthenticatedIngredientsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pantry': {
      id: '/_authenticated/pantry'
      path: '/pantry'
      fullPath: '/pantry'
      preLoaderRoute: typeof AuthenticatedPantryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/planner': {
      id: '/_authenticated/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof AuthenticatedPlannerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/spending': {
      id: '/_authenticated/spending'
      path: '/spending'
      fullPath: '/spending'
      preLoaderRoute: typeof AuthenticatedSpendingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/stores': {
      id: '/_authenticated/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof AuthenticatedStoresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/suggest': {
      id: '/_authenticated/suggest'
      path: '/suggest'
      fullPath: '/suggest'
      preLoaderRoute: typeof AuthenticatedSuggestRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/household/settings': {
      id: '/_authenticated/household/settings'
      path: '/household/settings'
      fullPath: '/household/settings'
      preLoaderRoute: typeof AuthenticatedHouseholdSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recipes/': {
      id: '/_authenticated/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof AuthenticatedRecipesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recipes/bulk-import': {
      id: '/_authenticated/recipes/bulk-import'
      path: '/recipes/bulk-import'
      fullPath: '/recipes/bulk-import'
      preLoaderRoute: typeof AuthenticatedRecipesBulkImportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recipes/import': {
      id: '/_authenticated/recipes/import'
      path: '/recipes/import'
      fullPath: '/recipes/import'
      preLoaderRoute: typeof AuthenticatedRecipesImportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recipes/new': {
      id: '/_authenticated/recipes/new'
      path: '/recipes/new'
      fullPath: '/recipes/new'
      preLoaderRoute: typeof AuthenticatedRecipesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/shopping-list/': {
      id: '/_authenticated/shopping-list/'
      path: '/shopping-list'
      fullPath: '/shopping-list/'
      preLoaderRoute: typeof AuthenticatedShoppingListIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/shopping-list/$listId': {
      id: '/_authenticated/shopping-list/$listId'
      path: '/shopping-list/$listId'
      fullPath: '/shopping-list/$listId'
      preLoaderRoute: typeof AuthenticatedShoppingListListIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recipes/$recipeId/': {
      id: '/_authenticated/recipes/$recipeId/'
      path: '/recipes/$recipeId'
      fullPath: '/recipes/$recipeId/'
      preLoaderRoute: typeof AuthenticatedRecipesRecipeIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recipes/$recipeId/edit': {
      id: '/_authenticated/recipes/$recipeId/edit'
      path: '/recipes/$recipeId/edit'
      fullPath: '/recipes/$recipeId/edit'
      preLoaderRoute: typeof AuthenticatedRecipesRecipeIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedIngredientsRoute: typeof AuthenticatedIngredientsRoute
  AuthenticatedPantryRoute: typeof AuthenticatedPantryRoute
  AuthenticatedPlannerRoute: typeof AuthenticatedPlannerRoute
  AuthenticatedSpendingRoute: typeof AuthenticatedSpendingRoute
  AuthenticatedStoresRoute: typeof AuthenticatedStoresRoute
  AuthenticatedSuggestRoute: typeof AuthenticatedSuggestRoute
  AuthenticatedHouseholdSettingsRoute: typeof AuthenticatedHouseholdSettingsRoute
  AuthenticatedRecipesBulkImportRoute: typeof AuthenticatedRecipesBulkImportRoute
  AuthenticatedRecipesImportRoute: typeof AuthenticatedRecipesImportRoute
  AuthenticatedRecipesNewRoute: typeof AuthenticatedRecipesNewRoute
  AuthenticatedShoppingListListIdRoute: typeof AuthenticatedShoppingListListIdRoute
  AuthenticatedRecipesIndexRoute: typeof AuthenticatedRecipesIndexRoute
  AuthenticatedShoppingListIndexRoute: typeof AuthenticatedShoppingListIndexRoute
  AuthenticatedRecipesRecipeIdEditRoute: typeof AuthenticatedRecipesRecipeIdEditRoute
  AuthenticatedRecipesRecipeIdIndexRoute: typeof AuthenticatedRecipesRecipeIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedIngredientsRoute: AuthenticatedIngredientsRoute,
  AuthenticatedPantryRoute: AuthenticatedPantryRoute,
  AuthenticatedPlannerRoute: AuthenticatedPlannerRoute,
  AuthenticatedSpendingRoute: AuthenticatedSpendingRoute,
  AuthenticatedStoresRoute: AuthenticatedStoresRoute,
  AuthenticatedSuggestRoute: AuthenticatedSuggestRoute,
  AuthenticatedHouseholdSettingsRoute: AuthenticatedHouseholdSettingsRoute,
  AuthenticatedRecipesBulkImportRoute: AuthenticatedRecipesBulkImportRoute,
  AuthenticatedRecipesImportRoute: AuthenticatedRecipesImportRoute,
  AuthenticatedRecipesNewRoute: AuthenticatedRecipesNewRoute,
  AuthenticatedShoppingListListIdRoute: AuthenticatedShoppingListListIdRoute,
  AuthenticatedRecipesIndexRoute: AuthenticatedRecipesIndexRoute,
  AuthenticatedShoppingListIndexRoute: AuthenticatedShoppingListIndexRoute,
  AuthenticatedRecipesRecipeIdEditRoute: AuthenticatedRecipesRecipeIdEditRoute,
  AuthenticatedRecipesRecipeIdIndexRoute:
    AuthenticatedRecipesRecipeIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  HealthRoute: HealthRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
