-- Slice 3 — Global canonical ingredient seed.
-- Reference data (household_id null) so new households don't start from zero.
-- Columns: name, aliases, category, default_unit, density_g_per_ml,
--          unit_size_quantity, unit_size_unit, count_to_gram.
-- Densities are for the common baking staples where volume<->mass matters most;
-- count_to_gram is set for items commonly given by count (eggs, garlic, etc.).
-- A starter set meant to grow toward ~500; add rows freely.

insert into public.canonical_ingredient
  (name, aliases, category, default_unit, density_g_per_ml, unit_size_quantity, unit_size_unit, count_to_gram)
values
  -- Dairy & eggs
  ('cream cheese', '{philadelphia,philly,neufchatel}', 'dairy', 'oz', 0.98, 8, 'oz', null),
  ('butter', '{unsalted butter,salted butter,sweet cream butter}', 'dairy', 'g', 0.911, 454, 'g', 113),
  ('whole milk', '{milk,vitamin d milk}', 'dairy', 'ml', 1.03, 3785, 'ml', null),
  ('buttermilk', '{}', 'dairy', 'ml', 1.03, 946, 'ml', null),
  ('heavy cream', '{heavy whipping cream,whipping cream,double cream}', 'dairy', 'ml', 1.0, 473, 'ml', null),
  ('sour cream', '{}', 'dairy', 'g', 1.0, 454, 'g', null),
  ('greek yogurt', '{yogurt,plain yogurt}', 'dairy', 'g', 1.03, 907, 'g', null),
  ('cheddar cheese', '{cheddar,sharp cheddar,shredded cheddar}', 'dairy', 'g', null, 227, 'g', null),
  ('mozzarella cheese', '{mozzarella,shredded mozzarella}', 'dairy', 'g', null, 227, 'g', null),
  ('parmesan cheese', '{parmesan,parmigiano,parmigiano reggiano,grated parmesan}', 'dairy', 'g', null, 170, 'g', null),
  ('feta cheese', '{feta,crumbled feta}', 'dairy', 'g', null, 170, 'g', null),
  ('cottage cheese', '{}', 'dairy', 'g', 1.0, 454, 'g', null),
  ('egg', '{eggs,large egg,large eggs}', 'dairy', 'each', null, 12, 'each', 50),
  ('egg yolk', '{egg yolks,yolk,yolks}', 'dairy', 'each', null, null, null, 18),
  ('egg white', '{egg whites}', 'dairy', 'each', null, null, null, 33),

  -- Baking & pantry staples (density matters here)
  ('all-purpose flour', '{flour,ap flour,plain flour,white flour}', 'baking', 'g', 0.53, 2270, 'g', null),
  ('bread flour', '{}', 'baking', 'g', 0.53, 2270, 'g', null),
  ('cake flour', '{}', 'baking', 'g', 0.49, 907, 'g', null),
  ('whole wheat flour', '{wholemeal flour}', 'baking', 'g', 0.51, 2270, 'g', null),
  ('granulated sugar', '{sugar,white sugar,caster sugar}', 'baking', 'g', 0.85, 1810, 'g', null),
  ('brown sugar', '{light brown sugar,dark brown sugar,packed brown sugar}', 'baking', 'g', 0.93, 454, 'g', null),
  ('powdered sugar', '{confectioners sugar,icing sugar,confectioners'' sugar}', 'baking', 'g', 0.56, 454, 'g', null),
  ('baking soda', '{sodium bicarbonate,bicarbonate of soda}', 'baking', 'g', 2.2, 454, 'g', null),
  ('baking powder', '{}', 'baking', 'g', 0.9, 227, 'g', null),
  ('cornstarch', '{corn starch,cornflour}', 'baking', 'g', 0.54, 454, 'g', null),
  ('cocoa powder', '{unsweetened cocoa,cocoa,dutch cocoa}', 'baking', 'g', 0.53, 227, 'g', null),
  ('vanilla extract', '{vanilla,pure vanilla extract}', 'baking', 'ml', 0.88, 118, 'ml', null),
  ('almond extract', '{}', 'baking', 'ml', 0.88, 30, 'ml', null),
  ('active dry yeast', '{yeast,instant yeast,dry yeast}', 'baking', 'g', 0.8, 7, 'g', null),
  ('chocolate chips', '{semisweet chocolate chips,chocolate morsels}', 'baking', 'g', 0.75, 340, 'g', null),
  ('dark chocolate', '{bittersweet chocolate,baking chocolate}', 'baking', 'g', 0.9, 113, 'g', null),
  ('rolled oats', '{oats,old-fashioned oats,oatmeal}', 'baking', 'g', 0.41, 510, 'g', null),
  ('honey', '{}', 'pantry', 'g', 1.42, 340, 'g', null),
  ('maple syrup', '{pure maple syrup}', 'pantry', 'ml', 1.37, 355, 'ml', null),
  ('molasses', '{}', 'pantry', 'ml', 1.4, 355, 'ml', null),
  ('peanut butter', '{}', 'pantry', 'g', 1.09, 462, 'g', null),
  ('cornmeal', '{polenta}', 'baking', 'g', 0.6, 907, 'g', null),
  ('graham cracker crumbs', '{}', 'baking', 'g', 0.42, 397, 'g', null),

  -- Oils, vinegars, condiments
  ('olive oil', '{extra-virgin olive oil,extra virgin olive oil,evoo}', 'pantry', 'ml', 0.915, 500, 'ml', null),
  ('vegetable oil', '{canola oil,neutral oil}', 'pantry', 'ml', 0.92, 946, 'ml', null),
  ('sesame oil', '{toasted sesame oil}', 'pantry', 'ml', 0.92, 148, 'ml', null),
  ('coconut oil', '{}', 'pantry', 'g', 0.92, 414, 'g', null),
  ('white vinegar', '{distilled vinegar}', 'pantry', 'ml', 1.01, 473, 'ml', null),
  ('apple cider vinegar', '{cider vinegar}', 'pantry', 'ml', 1.01, 473, 'ml', null),
  ('red wine vinegar', '{}', 'pantry', 'ml', 1.01, 355, 'ml', null),
  ('balsamic vinegar', '{}', 'pantry', 'ml', 1.06, 250, 'ml', null),
  ('rice vinegar', '{rice wine vinegar}', 'pantry', 'ml', 1.01, 296, 'ml', null),
  ('soy sauce', '{}', 'condiments', 'ml', 1.1, 296, 'ml', null),
  ('fish sauce', '{}', 'condiments', 'ml', 1.1, 200, 'ml', null),
  ('worcestershire sauce', '{}', 'condiments', 'ml', 1.1, 296, 'ml', null),
  ('hoisin sauce', '{}', 'condiments', 'g', 1.2, 240, 'g', null),
  ('sriracha', '{}', 'condiments', 'ml', 1.2, 482, 'ml', null),
  ('hot sauce', '{}', 'condiments', 'ml', 1.0, 148, 'ml', null),
  ('ketchup', '{catsup,tomato ketchup}', 'condiments', 'g', 1.14, 567, 'g', null),
  ('mustard', '{yellow mustard}', 'condiments', 'g', 1.0, 255, 'g', null),
  ('dijon mustard', '{}', 'condiments', 'g', 1.0, 215, 'g', null),
  ('mayonnaise', '{mayo}', 'condiments', 'g', 0.91, 887, 'g', null),
  ('barbecue sauce', '{bbq sauce}', 'condiments', 'g', 1.1, 510, 'g', null),
  ('tahini', '{}', 'condiments', 'g', 1.05, 454, 'g', null),
  ('pesto', '{basil pesto}', 'condiments', 'g', 0.95, 227, 'g', null),
  ('tomato paste', '{}', 'canned', 'g', 1.1, 170, 'g', null),
  ('marinara sauce', '{pasta sauce,tomato sauce}', 'canned', 'g', 1.03, 680, 'g', null),

  -- Canned & jarred
  ('canned diced tomatoes', '{diced tomatoes}', 'canned', 'oz', null, 14.5, 'oz', null),
  ('canned crushed tomatoes', '{crushed tomatoes}', 'canned', 'oz', null, 28, 'oz', null),
  ('canned whole tomatoes', '{whole peeled tomatoes,san marzano tomatoes}', 'canned', 'oz', null, 28, 'oz', null),
  ('tomato sauce', '{canned tomato sauce}', 'canned', 'oz', null, 15, 'oz', null),
  ('black beans', '{canned black beans}', 'canned', 'oz', null, 15, 'oz', null),
  ('chickpeas', '{garbanzo beans,canned chickpeas}', 'canned', 'oz', null, 15, 'oz', null),
  ('kidney beans', '{}', 'canned', 'oz', null, 15, 'oz', null),
  ('cannellini beans', '{white beans}', 'canned', 'oz', null, 15, 'oz', null),
  ('coconut milk', '{canned coconut milk,full-fat coconut milk}', 'canned', 'oz', null, 13.5, 'oz', null),
  ('sweetened condensed milk', '{condensed milk}', 'canned', 'oz', null, 14, 'oz', null),
  ('evaporated milk', '{}', 'canned', 'oz', null, 12, 'oz', null),
  ('diced green chiles', '{green chiles}', 'canned', 'oz', null, 4, 'oz', null),
  ('cream of mushroom soup', '{condensed cream of mushroom soup}', 'canned', 'oz', null, 10.5, 'oz', null),
  ('tuna', '{canned tuna}', 'canned', 'oz', null, 5, 'oz', null),

  -- Grains, pasta, rice
  ('white rice', '{long-grain white rice,long grain rice,rice}', 'pantry', 'g', 0.85, 907, 'g', null),
  ('brown rice', '{}', 'pantry', 'g', 0.82, 907, 'g', null),
  ('jasmine rice', '{}', 'pantry', 'g', 0.85, 907, 'g', null),
  ('basmati rice', '{}', 'pantry', 'g', 0.85, 907, 'g', null),
  ('spaghetti', '{}', 'pantry', 'g', null, 454, 'g', null),
  ('pasta', '{dried pasta,penne,rigatoni,macaroni}', 'pantry', 'g', null, 454, 'g', null),
  ('panko breadcrumbs', '{panko,breadcrumbs,bread crumbs}', 'pantry', 'g', 0.24, 227, 'g', null),
  ('quinoa', '{}', 'pantry', 'g', 0.85, 454, 'g', null),
  ('couscous', '{}', 'pantry', 'g', 0.7, 454, 'g', null),

  -- Produce — vegetables
  ('yellow onion', '{onion,onions,brown onion}', 'produce', 'each', null, null, null, 110),
  ('red onion', '{}', 'produce', 'each', null, null, null, 110),
  ('green onion', '{scallion,scallions,spring onion}', 'produce', 'bunch', null, 1, 'bunch', 15),
  ('garlic', '{garlic clove,garlic cloves}', 'produce', 'clove', null, 1, 'head', 5),
  ('carrot', '{carrots}', 'produce', 'each', null, 907, 'g', 60),
  ('celery', '{celery stalk,celery stalks}', 'produce', 'each', null, 1, 'bunch', 40),
  ('potato', '{potatoes,russet potato,russet potatoes}', 'produce', 'each', null, null, null, 170),
  ('sweet potato', '{sweet potatoes,yam}', 'produce', 'each', null, null, null, 130),
  ('tomato', '{tomatoes,roma tomato}', 'produce', 'each', null, null, null, 120),
  ('cherry tomatoes', '{grape tomatoes}', 'produce', 'g', null, 283, 'g', null),
  ('bell pepper', '{red bell pepper,green bell pepper,capsicum}', 'produce', 'each', null, null, null, 120),
  ('jalapeno', '{jalapeño,jalapenos}', 'produce', 'each', null, null, null, 14),
  ('cucumber', '{english cucumber}', 'produce', 'each', null, null, null, 300),
  ('zucchini', '{courgette}', 'produce', 'each', null, null, null, 200),
  ('eggplant', '{aubergine}', 'produce', 'each', null, null, null, 450),
  ('broccoli', '{}', 'produce', 'each', null, 1, 'head', 450),
  ('cauliflower', '{}', 'produce', 'each', null, 1, 'head', 600),
  ('mushrooms', '{white mushrooms,button mushrooms,cremini}', 'produce', 'g', null, 227, 'g', null),
  ('baby spinach', '{spinach}', 'produce', 'g', null, 142, 'g', null),
  ('kale', '{}', 'produce', 'bunch', null, 1, 'bunch', null),
  ('romaine lettuce', '{lettuce}', 'produce', 'head', null, 1, 'head', null),
  ('cabbage', '{green cabbage}', 'produce', 'each', null, 1, 'head', 900),
  ('corn', '{corn kernels,frozen corn,ear of corn}', 'produce', 'each', null, 340, 'g', 90),
  ('green beans', '{}', 'produce', 'g', null, 340, 'g', null),
  ('asparagus', '{}', 'produce', 'g', null, 454, 'g', null),
  ('butternut squash', '{}', 'produce', 'each', null, null, null, 1000),
  ('ginger', '{fresh ginger,ginger root}', 'produce', 'g', null, null, null, null),
  ('avocado', '{avocados}', 'produce', 'each', null, null, null, 150),

  -- Produce — fruit
  ('lemon', '{lemons}', 'produce', 'each', null, null, null, 100),
  ('lime', '{limes}', 'produce', 'each', null, null, null, 67),
  ('orange', '{oranges}', 'produce', 'each', null, null, null, 130),
  ('banana', '{bananas}', 'produce', 'each', null, null, null, 118),
  ('apple', '{apples,green apple,granny smith}', 'produce', 'each', null, null, null, 180),
  ('strawberries', '{strawberry}', 'produce', 'g', null, 454, 'g', null),
  ('blueberries', '{blueberry}', 'produce', 'g', null, 170, 'g', null),
  ('raspberries', '{raspberry}', 'produce', 'g', null, 170, 'g', null),

  -- Herbs & spices
  ('salt', '{kosher salt,table salt,sea salt,fine sea salt}', 'spices', 'g', 1.2, 737, 'g', null),
  ('black pepper', '{pepper,freshly ground black pepper,ground black pepper}', 'spices', 'g', 0.5, 100, 'g', null),
  ('ground cinnamon', '{cinnamon}', 'spices', 'g', 0.45, 60, 'g', null),
  ('ground cumin', '{cumin}', 'spices', 'g', 0.5, 60, 'g', null),
  ('chili powder', '{}', 'spices', 'g', 0.5, 70, 'g', null),
  ('smoked paprika', '{paprika}', 'spices', 'g', 0.46, 70, 'g', null),
  ('garlic powder', '{}', 'spices', 'g', 0.6, 90, 'g', null),
  ('onion powder', '{}', 'spices', 'g', 0.6, 90, 'g', null),
  ('dried oregano', '{oregano}', 'spices', 'g', 0.2, 30, 'g', null),
  ('italian seasoning', '{}', 'spices', 'g', 0.2, 30, 'g', null),
  ('ground turmeric', '{turmeric}', 'spices', 'g', 0.6, 60, 'g', null),
  ('ground nutmeg', '{nutmeg}', 'spices', 'g', 0.5, 50, 'g', null),
  ('red pepper flakes', '{crushed red pepper}', 'spices', 'g', 0.3, 50, 'g', null),
  ('cayenne pepper', '{cayenne}', 'spices', 'g', 0.5, 50, 'g', null),
  ('bay leaves', '{bay leaf}', 'spices', 'each', null, null, null, null),
  ('fresh basil', '{basil}', 'produce', 'g', null, 20, 'g', null),
  ('fresh cilantro', '{cilantro,coriander}', 'produce', 'bunch', null, 1, 'bunch', null),
  ('fresh parsley', '{parsley}', 'produce', 'bunch', null, 1, 'bunch', null),
  ('fresh thyme', '{thyme}', 'produce', 'g', null, 20, 'g', null),
  ('fresh rosemary', '{rosemary}', 'produce', 'g', null, 20, 'g', null),
  ('fresh dill', '{dill}', 'produce', 'g', null, 20, 'g', null),

  -- Meat & seafood
  ('ground beef', '{hamburger,minced beef,ground chuck}', 'meat', 'lb', null, 1, 'lb', null),
  ('ground turkey', '{}', 'meat', 'lb', null, 1, 'lb', null),
  ('ground pork', '{}', 'meat', 'lb', null, 1, 'lb', null),
  ('chicken breast', '{boneless skinless chicken breast,chicken breasts}', 'meat', 'lb', null, 1, 'lb', 170),
  ('chicken thigh', '{chicken thighs,boneless skinless chicken thighs}', 'meat', 'lb', null, 1, 'lb', 110),
  ('whole chicken', '{}', 'meat', 'lb', null, 5, 'lb', null),
  ('rotisserie chicken', '{}', 'meat', 'each', null, 1, 'each', 700),
  ('bacon', '{}', 'meat', 'g', null, 454, 'g', null),
  ('italian sausage', '{sausage}', 'meat', 'lb', null, 1, 'lb', null),
  ('pork shoulder', '{pork butt,boston butt}', 'meat', 'lb', null, 1, 'lb', null),
  ('ribeye steak', '{ribeye,steak}', 'meat', 'each', null, 1, 'each', 340),
  ('salmon', '{salmon fillet,salmon fillets}', 'seafood', 'lb', null, 1, 'lb', 170),
  ('shrimp', '{prawns,large shrimp}', 'seafood', 'lb', null, 1, 'lb', null),

  -- Bakery & misc
  ('bread', '{white bread,sandwich bread,loaf}', 'bakery', 'each', null, 1, 'each', null),
  ('flour tortillas', '{flour tortilla}', 'bakery', 'each', null, 8, 'each', null),
  ('corn tortillas', '{corn tortilla}', 'bakery', 'each', null, 12, 'each', null),
  ('hamburger buns', '{burger buns}', 'bakery', 'each', null, 8, 'each', null),

  -- Broths & liquids
  ('chicken broth', '{chicken stock,low-sodium chicken broth}', 'canned', 'ml', 1.0, 946, 'ml', null),
  ('beef broth', '{beef stock}', 'canned', 'ml', 1.0, 946, 'ml', null),
  ('vegetable broth', '{vegetable stock,veggie broth}', 'canned', 'ml', 1.0, 946, 'ml', null),
  ('water', '{}', 'pantry', 'ml', 1.0, null, null, null),
  ('dry white wine', '{white wine}', 'beverages', 'ml', 0.99, 750, 'ml', null),
  ('red wine', '{dry red wine}', 'beverages', 'ml', 0.99, 750, 'ml', null),

  -- Sweeteners & extras
  ('raisins', '{}', 'pantry', 'g', 0.8, 425, 'g', null),
  ('dried cranberries', '{craisins}', 'pantry', 'g', 0.8, 340, 'g', null),
  ('shredded coconut', '{sweetened coconut,desiccated coconut}', 'baking', 'g', 0.35, 397, 'g', null),
  ('walnuts', '{chopped walnuts}', 'baking', 'g', 0.5, 227, 'g', null),
  ('pecans', '{}', 'baking', 'g', 0.5, 227, 'g', null),
  ('almonds', '{sliced almonds,slivered almonds}', 'baking', 'g', 0.6, 227, 'g', null),
  ('marshmallows', '{mini marshmallows}', 'baking', 'g', 0.13, 283, 'g', null);
