-- Slice 3 (follow-up) — Expand the global canonical ingredient seed.
-- Same columns/conventions as 20260801165327_seed_canonical_ingredients.sql:
--   name, aliases, category, default_unit, density_g_per_ml,
--   unit_size_quantity, unit_size_unit, count_to_gram.
-- Deduplicated against the original 172 rows. Breadth over density: densities
-- are set only where volume<->mass conversion is common (liquids, oils, syrups);
-- package sizes are typical US grocery sizes so pricing has a sensible default.

insert into public.canonical_ingredient
  (name, aliases, category, default_unit, density_g_per_ml, unit_size_quantity, unit_size_unit, count_to_gram)
values
  -- Dairy & eggs
  ('2% milk', '{reduced fat milk,two percent milk}', 'dairy', 'ml', 1.03, 3785, 'ml', null),
  ('skim milk', '{nonfat milk,fat free milk}', 'dairy', 'ml', 1.03, 3785, 'ml', null),
  ('half and half', '{half & half}', 'dairy', 'ml', 1.01, 946, 'ml', null),
  ('ricotta cheese', '{ricotta}', 'dairy', 'g', 1.0, 425, 'g', null),
  ('swiss cheese', '{}', 'dairy', 'g', null, 227, 'g', null),
  ('provolone cheese', '{provolone}', 'dairy', 'g', null, 227, 'g', null),
  ('monterey jack cheese', '{monterey jack,jack cheese}', 'dairy', 'g', null, 227, 'g', null),
  ('pepper jack cheese', '{pepper jack}', 'dairy', 'g', null, 227, 'g', null),
  ('colby jack cheese', '{colby jack,colby}', 'dairy', 'g', null, 227, 'g', null),
  ('gouda cheese', '{gouda}', 'dairy', 'g', null, 227, 'g', null),
  ('gruyere cheese', '{gruyere}', 'dairy', 'g', null, 200, 'g', null),
  ('brie cheese', '{brie}', 'dairy', 'g', null, 227, 'g', null),
  ('goat cheese', '{chevre}', 'dairy', 'g', null, 113, 'g', null),
  ('blue cheese', '{gorgonzola,crumbled blue cheese}', 'dairy', 'g', null, 113, 'g', null),
  ('mascarpone', '{mascarpone cheese}', 'dairy', 'g', 1.0, 227, 'g', null),
  ('queso fresco', '{}', 'dairy', 'g', null, 283, 'g', null),
  ('cotija cheese', '{cotija}', 'dairy', 'g', null, 283, 'g', null),
  ('american cheese', '{american cheese slices}', 'dairy', 'g', null, 340, 'g', null),
  ('string cheese', '{mozzarella string cheese}', 'dairy', 'each', null, 12, 'each', null),
  ('plain yogurt', '{}', 'dairy', 'g', 1.03, 907, 'g', null),
  ('vanilla yogurt', '{}', 'dairy', 'g', 1.03, 907, 'g', null),
  ('whipped cream', '{}', 'dairy', 'g', null, 226, 'g', null),
  ('margarine', '{}', 'dairy', 'g', 0.91, 454, 'g', 113),
  ('ghee', '{clarified butter}', 'dairy', 'g', 0.91, 397, 'g', null),
  ('almond milk', '{unsweetened almond milk}', 'dairy', 'ml', 1.0, 1893, 'ml', null),
  ('oat milk', '{}', 'dairy', 'ml', 1.02, 1420, 'ml', null),
  ('soy milk', '{}', 'dairy', 'ml', 1.02, 1893, 'ml', null),

  -- Meat & poultry
  ('chicken wings', '{wings,chicken wing}', 'meat', 'lb', null, 1, 'lb', null),
  ('chicken drumsticks', '{drumsticks}', 'meat', 'lb', null, 1, 'lb', null),
  ('chicken tenders', '{chicken tenderloins}', 'meat', 'lb', null, 1, 'lb', null),
  ('boneless skinless chicken breast', '{}', 'meat', 'lb', null, 1, 'lb', null),
  ('pork chops', '{pork chop,bone-in pork chops}', 'meat', 'lb', null, 1, 'lb', null),
  ('pork tenderloin', '{}', 'meat', 'lb', null, 1, 'lb', null),
  ('pork loin', '{}', 'meat', 'lb', null, 1, 'lb', null),
  ('baby back ribs', '{pork ribs,ribs}', 'meat', 'lb', null, 1, 'lb', null),
  ('ground chicken', '{}', 'meat', 'lb', null, 1, 'lb', null),
  ('ground lamb', '{}', 'meat', 'lb', null, 1, 'lb', null),
  ('lamb chops', '{}', 'meat', 'lb', null, 1, 'lb', null),
  ('leg of lamb', '{}', 'meat', 'lb', null, 1, 'lb', null),
  ('sirloin steak', '{top sirloin}', 'meat', 'lb', null, 1, 'lb', null),
  ('flank steak', '{}', 'meat', 'lb', null, 1, 'lb', null),
  ('skirt steak', '{}', 'meat', 'lb', null, 1, 'lb', null),
  ('new york strip steak', '{strip steak}', 'meat', 'lb', null, 1, 'lb', null),
  ('filet mignon', '{beef tenderloin steak}', 'meat', 'lb', null, 1, 'lb', null),
  ('chuck roast', '{beef chuck}', 'meat', 'lb', null, 1, 'lb', null),
  ('beef brisket', '{brisket}', 'meat', 'lb', null, 1, 'lb', null),
  ('stew meat', '{beef stew meat,stewing beef}', 'meat', 'lb', null, 1, 'lb', null),
  ('short ribs', '{beef short ribs}', 'meat', 'lb', null, 1, 'lb', null),
  ('corned beef', '{}', 'meat', 'lb', null, 1, 'lb', null),
  ('hot dogs', '{hot dog,frankfurters}', 'meat', 'each', null, 8, 'each', null),
  ('bratwurst', '{brats}', 'meat', 'each', null, 5, 'each', null),
  ('breakfast sausage', '{sausage links,pork sausage}', 'meat', 'g', null, 340, 'g', null),
  ('chorizo', '{}', 'meat', 'g', null, 340, 'g', null),
  ('kielbasa', '{polish sausage}', 'meat', 'g', null, 397, 'g', null),
  ('pepperoni', '{}', 'meat', 'g', null, 170, 'g', null),
  ('salami', '{}', 'meat', 'g', null, 227, 'g', null),
  ('prosciutto', '{}', 'meat', 'g', null, 113, 'g', null),
  ('deli ham', '{sliced ham}', 'meat', 'g', null, 227, 'g', null),
  ('ham', '{}', 'meat', 'lb', null, 1, 'lb', null),
  ('deli turkey', '{sliced turkey,turkey lunch meat}', 'meat', 'g', null, 227, 'g', null),
  ('turkey breast', '{}', 'meat', 'lb', null, 1, 'lb', null),

  -- Seafood
  ('cod', '{cod fillets,cod fillet}', 'seafood', 'lb', null, 1, 'lb', null),
  ('tilapia', '{tilapia fillets}', 'seafood', 'lb', null, 1, 'lb', null),
  ('halibut', '{}', 'seafood', 'lb', null, 1, 'lb', null),
  ('mahi mahi', '{}', 'seafood', 'lb', null, 1, 'lb', null),
  ('catfish', '{}', 'seafood', 'lb', null, 1, 'lb', null),
  ('trout', '{}', 'seafood', 'lb', null, 1, 'lb', null),
  ('sea bass', '{}', 'seafood', 'lb', null, 1, 'lb', null),
  ('sardines', '{canned sardines}', 'seafood', 'oz', null, 4, 'oz', null),
  ('anchovies', '{anchovy}', 'seafood', 'oz', null, 2, 'oz', null),
  ('scallops', '{sea scallops}', 'seafood', 'lb', null, 1, 'lb', null),
  ('mussels', '{}', 'seafood', 'lb', null, 1, 'lb', null),
  ('clams', '{}', 'seafood', 'lb', null, 1, 'lb', null),
  ('crab meat', '{lump crab meat,crab}', 'seafood', 'oz', null, 8, 'oz', null),
  ('lobster', '{lobster tail,lobster tails}', 'seafood', 'lb', null, 1, 'lb', null),
  ('smoked salmon', '{lox}', 'seafood', 'oz', null, 4, 'oz', null),
  ('imitation crab', '{surimi}', 'seafood', 'oz', null, 8, 'oz', null),

  -- Produce — vegetables
  ('spinach', '{fresh spinach}', 'produce', 'g', null, 283, 'g', null),
  ('arugula', '{}', 'produce', 'g', null, 142, 'g', null),
  ('mixed greens', '{spring mix,salad greens,mesclun}', 'produce', 'g', null, 142, 'g', null),
  ('iceberg lettuce', '{}', 'produce', 'each', null, 1, 'each', 600),
  ('brussels sprouts', '{}', 'produce', 'g', null, 454, 'g', null),
  ('red cabbage', '{}', 'produce', 'each', null, 1, 'each', 900),
  ('snap peas', '{sugar snap peas}', 'produce', 'g', null, 227, 'g', null),
  ('snow peas', '{}', 'produce', 'g', null, 227, 'g', null),
  ('leek', '{leeks}', 'produce', 'each', null, 1, 'each', 89),
  ('shallot', '{shallots}', 'produce', 'each', null, 1, 'each', 40),
  ('fennel', '{fennel bulb}', 'produce', 'each', null, 1, 'each', 234),
  ('radish', '{radishes}', 'produce', 'g', null, 170, 'g', null),
  ('beet', '{beets,beetroot}', 'produce', 'each', null, 1, 'each', 82),
  ('turnip', '{turnips}', 'produce', 'each', null, 1, 'each', 122),
  ('parsnip', '{parsnips}', 'produce', 'each', null, 1, 'each', 133),
  ('acorn squash', '{}', 'produce', 'each', null, 1, 'each', 560),
  ('spaghetti squash', '{}', 'produce', 'each', null, 1, 'each', 1000),
  ('artichoke', '{artichokes}', 'produce', 'each', null, 1, 'each', 128),
  ('okra', '{}', 'produce', 'g', null, 227, 'g', null),
  ('bok choy', '{pak choi,baby bok choy}', 'produce', 'each', null, 1, 'each', 200),
  ('napa cabbage', '{chinese cabbage}', 'produce', 'each', null, 1, 'each', 840),
  ('collard greens', '{collards}', 'produce', 'g', null, 340, 'g', null),
  ('swiss chard', '{chard}', 'produce', 'g', null, 340, 'g', null),
  ('poblano pepper', '{poblano,poblano peppers}', 'produce', 'each', null, 1, 'each', 17),
  ('serrano pepper', '{serrano,serrano peppers}', 'produce', 'each', null, 1, 'each', 6),
  ('habanero pepper', '{habanero}', 'produce', 'each', null, 1, 'each', 8),
  ('anaheim pepper', '{anaheim}', 'produce', 'each', null, 1, 'each', 40),
  ('portobello mushroom', '{portobello mushrooms,portabella}', 'produce', 'each', null, 1, 'each', 84),
  ('cremini mushroom', '{cremini mushrooms,baby bella,baby portobello}', 'produce', 'g', null, 227, 'g', null),
  ('shiitake mushroom', '{shiitake mushrooms,shiitake}', 'produce', 'g', null, 113, 'g', null),
  ('white onion', '{}', 'produce', 'each', null, 1, 'each', 110),
  ('red bell pepper', '{red pepper}', 'produce', 'each', null, 1, 'each', 119),
  ('green bell pepper', '{green pepper}', 'produce', 'each', null, 1, 'each', 119),
  ('yellow bell pepper', '{yellow pepper}', 'produce', 'each', null, 1, 'each', 119),
  ('water chestnuts', '{}', 'canned', 'oz', null, 8, 'oz', null),
  ('bean sprouts', '{}', 'produce', 'g', null, 340, 'g', null),
  ('edamame', '{}', 'frozen', 'g', null, 454, 'g', null),
  ('plantain', '{plantains}', 'produce', 'each', null, 1, 'each', 179),
  ('butter lettuce', '{bibb lettuce,boston lettuce}', 'produce', 'each', null, 1, 'each', 160),
  ('green cabbage', '{}', 'produce', 'each', null, 1, 'each', 900),

  -- Produce — fruit
  ('grapes', '{red grapes,green grapes}', 'produce', 'g', null, 907, 'g', null),
  ('pineapple', '{}', 'produce', 'each', null, 1, 'each', 905),
  ('mango', '{mangoes}', 'produce', 'each', null, 1, 'each', 200),
  ('watermelon', '{}', 'produce', 'each', null, 1, 'each', 4500),
  ('cantaloupe', '{}', 'produce', 'each', null, 1, 'each', 550),
  ('honeydew melon', '{honeydew}', 'produce', 'each', null, 1, 'each', 1300),
  ('peach', '{peaches}', 'produce', 'each', null, 1, 'each', 150),
  ('pear', '{pears}', 'produce', 'each', null, 1, 'each', 178),
  ('plum', '{plums}', 'produce', 'each', null, 1, 'each', 66),
  ('nectarine', '{nectarines}', 'produce', 'each', null, 1, 'each', 142),
  ('apricot', '{apricots}', 'produce', 'each', null, 1, 'each', 35),
  ('cherries', '{fresh cherries}', 'produce', 'g', null, 454, 'g', null),
  ('kiwi', '{kiwis,kiwifruit}', 'produce', 'each', null, 1, 'each', 69),
  ('pomegranate', '{}', 'produce', 'each', null, 1, 'each', 282),
  ('blackberries', '{}', 'produce', 'g', null, 170, 'g', null),
  ('grapefruit', '{}', 'produce', 'each', null, 1, 'each', 246),
  ('clementine', '{clementines,cuties,mandarin oranges}', 'produce', 'each', null, 1, 'each', 74),
  ('cranberries', '{fresh cranberries}', 'produce', 'g', null, 340, 'g', null),
  ('papaya', '{}', 'produce', 'each', null, 1, 'each', 500),
  ('rhubarb', '{}', 'produce', 'g', null, 340, 'g', null),
  ('lemon juice', '{fresh lemon juice}', 'produce', 'ml', 1.03, 946, 'ml', null),
  ('lime juice', '{fresh lime juice}', 'produce', 'ml', 1.03, 946, 'ml', null),

  -- Grains, pasta, rice, noodles
  ('penne', '{penne pasta}', 'pantry', 'g', null, 454, 'g', null),
  ('rigatoni', '{}', 'pantry', 'g', null, 454, 'g', null),
  ('fettuccine', '{}', 'pantry', 'g', null, 454, 'g', null),
  ('linguine', '{}', 'pantry', 'g', null, 454, 'g', null),
  ('lasagna noodles', '{lasagne noodles}', 'pantry', 'g', null, 454, 'g', null),
  ('egg noodles', '{}', 'pantry', 'g', null, 340, 'g', null),
  ('orzo', '{}', 'pantry', 'g', null, 454, 'g', null),
  ('farfalle', '{bow tie pasta,bowtie pasta}', 'pantry', 'g', null, 454, 'g', null),
  ('rotini', '{}', 'pantry', 'g', null, 454, 'g', null),
  ('elbow macaroni', '{elbows}', 'pantry', 'g', null, 454, 'g', null),
  ('ramen noodles', '{instant ramen}', 'pantry', 'each', null, 6, 'each', null),
  ('rice noodles', '{}', 'pantry', 'g', null, 340, 'g', null),
  ('soba noodles', '{}', 'pantry', 'g', null, 340, 'g', null),
  ('udon noodles', '{udon}', 'pantry', 'g', null, 340, 'g', null),
  ('gnocchi', '{}', 'pantry', 'g', null, 500, 'g', null),
  ('wild rice', '{}', 'pantry', 'g', 0.85, 454, 'g', null),
  ('arborio rice', '{risotto rice}', 'pantry', 'g', 0.85, 907, 'g', null),
  ('long grain white rice', '{}', 'pantry', 'g', 0.85, 907, 'g', null),
  ('barley', '{pearl barley}', 'pantry', 'g', 0.8, 454, 'g', null),
  ('farro', '{}', 'pantry', 'g', 0.8, 454, 'g', null),
  ('bulgur', '{bulgur wheat}', 'pantry', 'g', 0.7, 454, 'g', null),
  ('steel cut oats', '{}', 'pantry', 'g', 0.45, 680, 'g', null),
  ('grits', '{}', 'pantry', 'g', 0.6, 680, 'g', null),
  ('plain breadcrumbs', '{}', 'pantry', 'g', 0.45, 425, 'g', null),
  ('italian breadcrumbs', '{seasoned breadcrumbs}', 'pantry', 'g', 0.45, 425, 'g', null),

  -- Canned, jarred & beans
  ('pinto beans', '{canned pinto beans}', 'canned', 'oz', null, 15, 'oz', null),
  ('refried beans', '{}', 'canned', 'oz', null, 16, 'oz', null),
  ('great northern beans', '{}', 'canned', 'oz', null, 15, 'oz', null),
  ('navy beans', '{}', 'canned', 'oz', null, 15, 'oz', null),
  ('lima beans', '{butter beans}', 'canned', 'oz', null, 15, 'oz', null),
  ('black-eyed peas', '{black eyed peas}', 'canned', 'oz', null, 15, 'oz', null),
  ('lentils', '{dried lentils,brown lentils}', 'pantry', 'g', 0.85, 454, 'g', null),
  ('red lentils', '{}', 'pantry', 'g', 0.85, 454, 'g', null),
  ('split peas', '{}', 'pantry', 'g', 0.85, 454, 'g', null),
  ('canned corn', '{sweet corn,whole kernel corn}', 'canned', 'oz', null, 15, 'oz', null),
  ('canned green beans', '{}', 'canned', 'oz', null, 14, 'oz', null),
  ('canned peas', '{}', 'canned', 'oz', null, 15, 'oz', null),
  ('pumpkin puree', '{canned pumpkin,pure pumpkin}', 'canned', 'oz', null, 15, 'oz', null),
  ('cream of chicken soup', '{}', 'canned', 'oz', null, 10.5, 'oz', null),
  ('cream of celery soup', '{}', 'canned', 'oz', null, 10.5, 'oz', null),
  ('tomato soup', '{}', 'canned', 'oz', null, 10.75, 'oz', null),
  ('fire roasted tomatoes', '{canned fire roasted tomatoes}', 'canned', 'oz', null, 14.5, 'oz', null),
  ('tomato puree', '{}', 'canned', 'oz', null, 29, 'oz', null),
  ('sun-dried tomatoes', '{sundried tomatoes}', 'canned', 'oz', null, 8.5, 'oz', null),
  ('roasted red peppers', '{jarred roasted red peppers}', 'canned', 'oz', null, 12, 'oz', null),
  ('artichoke hearts', '{}', 'canned', 'oz', null, 14, 'oz', null),
  ('black olives', '{sliced black olives}', 'canned', 'oz', null, 6, 'oz', null),
  ('green olives', '{}', 'canned', 'oz', null, 7, 'oz', null),
  ('kalamata olives', '{}', 'canned', 'oz', null, 8, 'oz', null),
  ('capers', '{}', 'condiments', 'oz', null, 3.5, 'oz', null),
  ('dill pickles', '{pickles}', 'canned', 'oz', null, 24, 'oz', null),
  ('pickle relish', '{sweet relish,relish}', 'condiments', 'oz', null, 10, 'oz', null),
  ('sauerkraut', '{}', 'canned', 'oz', null, 14, 'oz', null),
  ('salsa', '{jarred salsa}', 'condiments', 'oz', null, 16, 'oz', null),
  ('enchilada sauce', '{}', 'canned', 'oz', null, 10, 'oz', null),
  ('chipotle in adobo', '{chipotle peppers in adobo,chipotles in adobo}', 'canned', 'oz', null, 7, 'oz', null),
  ('applesauce', '{unsweetened applesauce}', 'canned', 'oz', null, 24, 'oz', null),
  ('cranberry sauce', '{}', 'canned', 'oz', null, 14, 'oz', null),

  -- Condiments, sauces & dressings
  ('ranch dressing', '{ranch}', 'condiments', 'ml', 1.0, 473, 'ml', null),
  ('italian dressing', '{}', 'condiments', 'ml', 1.0, 473, 'ml', null),
  ('caesar dressing', '{}', 'condiments', 'ml', 1.0, 473, 'ml', null),
  ('blue cheese dressing', '{}', 'condiments', 'ml', 1.0, 473, 'ml', null),
  ('balsamic vinaigrette', '{}', 'condiments', 'ml', 1.0, 355, 'ml', null),
  ('honey mustard', '{}', 'condiments', 'g', 1.1, 340, 'g', null),
  ('whole grain mustard', '{grainy mustard}', 'condiments', 'g', 1.0, 215, 'g', null),
  ('oyster sauce', '{}', 'condiments', 'ml', 1.2, 510, 'ml', null),
  ('teriyaki sauce', '{}', 'condiments', 'ml', 1.1, 296, 'ml', null),
  ('sweet chili sauce', '{thai sweet chili sauce}', 'condiments', 'ml', 1.2, 355, 'ml', null),
  ('chili garlic sauce', '{}', 'condiments', 'g', 1.1, 226, 'g', null),
  ('sambal oelek', '{}', 'condiments', 'g', 1.1, 226, 'g', null),
  ('gochujang', '{korean chili paste}', 'condiments', 'g', 1.2, 500, 'g', null),
  ('miso paste', '{miso,white miso}', 'condiments', 'g', 1.2, 340, 'g', null),
  ('red curry paste', '{}', 'condiments', 'g', 1.1, 113, 'g', null),
  ('green curry paste', '{}', 'condiments', 'g', 1.1, 113, 'g', null),
  ('tamari', '{}', 'condiments', 'ml', 1.1, 296, 'ml', null),
  ('mirin', '{}', 'condiments', 'ml', 1.1, 296, 'ml', null),
  ('harissa', '{harissa paste}', 'condiments', 'g', 1.1, 170, 'g', null),
  ('buffalo sauce', '{buffalo wing sauce}', 'condiments', 'ml', 1.0, 355, 'ml', null),
  ('horseradish', '{prepared horseradish}', 'condiments', 'g', 1.0, 170, 'g', null),
  ('tartar sauce', '{}', 'condiments', 'g', 0.95, 226, 'g', null),
  ('steak sauce', '{a1 sauce}', 'condiments', 'ml', 1.1, 283, 'ml', null),
  ('strawberry jam', '{strawberry preserves}', 'condiments', 'g', 1.3, 340, 'g', null),
  ('grape jelly', '{}', 'condiments', 'g', 1.3, 510, 'g', null),
  ('raspberry jam', '{raspberry preserves}', 'condiments', 'g', 1.3, 340, 'g', null),
  ('orange marmalade', '{marmalade}', 'condiments', 'g', 1.3, 340, 'g', null),
  ('apricot preserves', '{}', 'condiments', 'g', 1.3, 340, 'g', null),
  ('hazelnut spread', '{nutella}', 'condiments', 'g', 1.2, 370, 'g', null),

  -- Oils & vinegars
  ('avocado oil', '{}', 'pantry', 'ml', 0.91, 500, 'ml', null),
  ('peanut oil', '{}', 'pantry', 'ml', 0.92, 710, 'ml', null),
  ('grapeseed oil', '{}', 'pantry', 'ml', 0.92, 500, 'ml', null),
  ('cooking spray', '{nonstick cooking spray,pam}', 'pantry', 'each', null, 1, 'each', null),
  ('chili oil', '{}', 'pantry', 'ml', 0.92, 240, 'ml', null),
  ('white wine vinegar', '{}', 'pantry', 'ml', 1.01, 473, 'ml', null),
  ('sherry vinegar', '{}', 'pantry', 'ml', 1.01, 355, 'ml', null),
  ('malt vinegar', '{}', 'pantry', 'ml', 1.01, 355, 'ml', null),

  -- Herbs & spices
  ('paprika', '{sweet paprika}', 'spices', 'g', null, 71, 'g', null),
  ('ground ginger', '{}', 'spices', 'g', null, 45, 'g', null),
  ('ground allspice', '{allspice}', 'spices', 'g', null, 50, 'g', null),
  ('ground cloves', '{}', 'spices', 'g', null, 50, 'g', null),
  ('ground coriander', '{}', 'spices', 'g', null, 43, 'g', null),
  ('fennel seeds', '{}', 'spices', 'g', null, 43, 'g', null),
  ('mustard seeds', '{}', 'spices', 'g', null, 71, 'g', null),
  ('caraway seeds', '{}', 'spices', 'g', null, 50, 'g', null),
  ('dried basil', '{}', 'spices', 'g', null, 14, 'g', null),
  ('dried thyme', '{}', 'spices', 'g', null, 14, 'g', null),
  ('dried rosemary', '{}', 'spices', 'g', null, 20, 'g', null),
  ('dried parsley', '{}', 'spices', 'g', null, 14, 'g', null),
  ('dried sage', '{}', 'spices', 'g', null, 14, 'g', null),
  ('herbs de provence', '{herbes de provence}', 'spices', 'g', null, 21, 'g', null),
  ('curry powder', '{}', 'spices', 'g', null, 85, 'g', null),
  ('garam masala', '{}', 'spices', 'g', null, 85, 'g', null),
  ('cajun seasoning', '{}', 'spices', 'g', null, 71, 'g', null),
  ('taco seasoning', '{}', 'spices', 'g', null, 28, 'g', null),
  ('old bay seasoning', '{old bay}', 'spices', 'g', null, 170, 'g', null),
  ('poultry seasoning', '{}', 'spices', 'g', null, 14, 'g', null),
  ('chinese five spice', '{five spice}', 'spices', 'g', null, 50, 'g', null),
  ('cardamom', '{ground cardamom}', 'spices', 'g', null, 45, 'g', null),
  ('white pepper', '{ground white pepper}', 'spices', 'g', null, 50, 'g', null),
  ('sea salt', '{}', 'spices', 'g', null, 737, 'g', null),
  ('kosher salt', '{}', 'spices', 'g', null, 1360, 'g', null),
  ('garlic salt', '{}', 'spices', 'g', null, 149, 'g', null),
  ('everything bagel seasoning', '{everything but the bagel}', 'spices', 'g', null, 100, 'g', null),
  ('ranch seasoning', '{ranch seasoning mix,ranch dressing mix}', 'spices', 'g', null, 28, 'g', null),
  ('lemon pepper', '{lemon pepper seasoning}', 'spices', 'g', null, 100, 'g', null),
  ('fresh mint', '{mint}', 'produce', 'g', null, 20, 'g', null),
  ('fresh oregano', '{}', 'produce', 'g', null, 20, 'g', null),
  ('fresh chives', '{chives}', 'produce', 'g', null, 20, 'g', null),
  ('fresh sage', '{}', 'produce', 'g', null, 20, 'g', null),
  ('cinnamon stick', '{cinnamon sticks}', 'spices', 'each', null, 8, 'each', null),

  -- Nuts, seeds & butters
  ('peanuts', '{}', 'snacks', 'g', null, 454, 'g', null),
  ('cashews', '{}', 'snacks', 'g', null, 340, 'g', null),
  ('pistachios', '{}', 'snacks', 'g', null, 340, 'g', null),
  ('hazelnuts', '{filberts}', 'baking', 'g', null, 227, 'g', null),
  ('pine nuts', '{pignoli}', 'baking', 'g', null, 113, 'g', null),
  ('sunflower seeds', '{}', 'snacks', 'g', null, 227, 'g', null),
  ('pumpkin seeds', '{pepitas}', 'snacks', 'g', null, 227, 'g', null),
  ('chia seeds', '{}', 'pantry', 'g', null, 340, 'g', null),
  ('flax seeds', '{flaxseed,ground flaxseed}', 'pantry', 'g', null, 340, 'g', null),
  ('sesame seeds', '{}', 'spices', 'g', null, 100, 'g', null),
  ('almond butter', '{}', 'pantry', 'g', 1.09, 340, 'g', null),
  ('cashew butter', '{}', 'pantry', 'g', 1.09, 340, 'g', null),
  ('mixed nuts', '{}', 'snacks', 'g', null, 454, 'g', null),

  -- Baking add-ins & mixes
  ('self-rising flour', '{self rising flour}', 'baking', 'g', 0.53, 2270, 'g', null),
  ('almond flour', '{almond meal}', 'baking', 'g', 0.4, 340, 'g', null),
  ('coconut flour', '{}', 'baking', 'g', 0.51, 454, 'g', null),
  ('cream of tartar', '{}', 'baking', 'g', null, 100, 'g', null),
  ('unflavored gelatin', '{gelatin}', 'baking', 'g', null, 28, 'g', null),
  ('white chocolate', '{white chocolate chips}', 'baking', 'g', 0.9, 340, 'g', null),
  ('milk chocolate', '{milk chocolate chips}', 'baking', 'g', 0.9, 340, 'g', null),
  ('unsweetened chocolate', '{}', 'baking', 'g', 0.9, 113, 'g', null),
  ('butterscotch chips', '{}', 'baking', 'g', 0.75, 311, 'g', null),
  ('corn syrup', '{light corn syrup}', 'baking', 'ml', 1.38, 473, 'ml', null),
  ('agave nectar', '{agave syrup,agave}', 'pantry', 'ml', 1.37, 330, 'ml', null),
  ('shortening', '{vegetable shortening,crisco}', 'baking', 'g', 0.92, 454, 'g', null),
  ('lard', '{}', 'baking', 'g', 0.92, 454, 'g', null),
  ('pumpkin pie spice', '{}', 'spices', 'g', null, 45, 'g', null),
  ('apple pie spice', '{}', 'spices', 'g', null, 45, 'g', null),
  ('espresso powder', '{instant espresso powder}', 'baking', 'g', null, 85, 'g', null),
  ('pie crust', '{refrigerated pie crust,pie dough}', 'baking', 'each', null, 2, 'each', null),
  ('puff pastry', '{}', 'frozen', 'g', null, 490, 'g', null),
  ('pizza dough', '{}', 'bakery', 'g', null, 454, 'g', null),
  ('crescent roll dough', '{crescent rolls}', 'bakery', 'each', null, 8, 'each', null),
  ('cake mix', '{boxed cake mix}', 'baking', 'oz', null, 15.25, 'oz', null),
  ('brownie mix', '{}', 'baking', 'oz', null, 18, 'oz', null),

  -- Bakery & tortillas
  ('white bread', '{white sandwich bread}', 'bakery', 'each', null, 1, 'each', 567),
  ('whole wheat bread', '{wheat bread}', 'bakery', 'each', null, 1, 'each', 567),
  ('sourdough bread', '{sourdough}', 'bakery', 'each', null, 1, 'each', 567),
  ('baguette', '{french bread}', 'bakery', 'each', null, 1, 'each', 250),
  ('ciabatta', '{ciabatta bread}', 'bakery', 'each', null, 1, 'each', 300),
  ('dinner rolls', '{}', 'bakery', 'each', null, 12, 'each', null),
  ('hot dog buns', '{}', 'bakery', 'each', null, 8, 'each', null),
  ('english muffins', '{english muffin}', 'bakery', 'each', null, 6, 'each', null),
  ('bagels', '{bagel}', 'bakery', 'each', null, 6, 'each', null),
  ('croissants', '{croissant}', 'bakery', 'each', null, 4, 'each', null),
  ('pita bread', '{pita,pitas}', 'bakery', 'each', null, 6, 'each', null),
  ('naan', '{naan bread}', 'bakery', 'each', null, 4, 'each', null),
  ('brioche buns', '{brioche}', 'bakery', 'each', null, 4, 'each', null),
  ('taco shells', '{hard taco shells}', 'bakery', 'each', null, 12, 'each', null),
  ('tortilla chips', '{corn chips}', 'snacks', 'oz', null, 12, 'oz', null),
  ('wonton wrappers', '{}', 'produce', 'each', null, 50, 'each', null),

  -- Frozen
  ('frozen peas', '{}', 'frozen', 'g', null, 454, 'g', null),
  ('frozen corn', '{}', 'frozen', 'g', null, 454, 'g', null),
  ('frozen mixed vegetables', '{frozen vegetables}', 'frozen', 'g', null, 454, 'g', null),
  ('frozen broccoli', '{}', 'frozen', 'g', null, 340, 'g', null),
  ('frozen spinach', '{}', 'frozen', 'g', null, 284, 'g', null),
  ('frozen berries', '{mixed berries}', 'frozen', 'g', null, 340, 'g', null),
  ('frozen strawberries', '{}', 'frozen', 'g', null, 454, 'g', null),
  ('frozen blueberries', '{}', 'frozen', 'g', null, 340, 'g', null),
  ('frozen mango', '{}', 'frozen', 'g', null, 454, 'g', null),
  ('french fries', '{frozen french fries}', 'frozen', 'g', null, 907, 'g', null),
  ('frozen hash browns', '{hash browns}', 'frozen', 'g', null, 907, 'g', null),
  ('vanilla ice cream', '{ice cream}', 'frozen', 'ml', null, 1420, 'ml', null),
  ('whipped topping', '{cool whip}', 'frozen', 'oz', null, 8, 'oz', null),
  ('frozen shrimp', '{}', 'frozen', 'lb', null, 1, 'lb', null),
  ('frozen pizza', '{}', 'frozen', 'each', null, 1, 'each', null),
  ('frozen waffles', '{}', 'frozen', 'each', null, 10, 'each', null),

  -- Breakfast & snacks
  ('cereal', '{breakfast cereal}', 'breakfast', 'oz', null, 18, 'oz', null),
  ('granola', '{}', 'breakfast', 'g', null, 340, 'g', null),
  ('cornflakes', '{corn flakes}', 'breakfast', 'oz', null, 18, 'oz', null),
  ('granola bars', '{granola bar}', 'snacks', 'each', null, 8, 'each', null),
  ('pancake mix', '{}', 'breakfast', 'oz', null, 32, 'oz', null),
  ('pancake syrup', '{breakfast syrup}', 'breakfast', 'ml', 1.33, 710, 'ml', null),
  ('instant oatmeal', '{oatmeal packets}', 'breakfast', 'each', null, 10, 'each', null),
  ('potato chips', '{chips}', 'snacks', 'oz', null, 8, 'oz', null),
  ('pretzels', '{}', 'snacks', 'oz', null, 16, 'oz', null),
  ('popcorn', '{microwave popcorn}', 'snacks', 'each', null, 6, 'each', null),
  ('crackers', '{}', 'snacks', 'oz', null, 16, 'oz', null),
  ('saltine crackers', '{saltines}', 'snacks', 'oz', null, 16, 'oz', null),
  ('graham crackers', '{}', 'snacks', 'oz', null, 14.4, 'oz', null),
  ('hummus', '{}', 'snacks', 'oz', null, 10, 'oz', null),
  ('guacamole', '{}', 'produce', 'oz', null, 8, 'oz', null),
  ('beef jerky', '{jerky}', 'snacks', 'oz', null, 3, 'oz', null),
  ('dried apricots', '{}', 'snacks', 'g', null, 227, 'g', null),

  -- Beverages, broths & bouillon
  ('orange juice', '{oj}', 'beverages', 'ml', 1.04, 1750, 'ml', null),
  ('apple juice', '{}', 'beverages', 'ml', 1.04, 1890, 'ml', null),
  ('cranberry juice', '{}', 'beverages', 'ml', 1.04, 1890, 'ml', null),
  ('lemonade', '{}', 'beverages', 'ml', 1.04, 1890, 'ml', null),
  ('ground coffee', '{coffee}', 'beverages', 'g', null, 340, 'g', null),
  ('coffee beans', '{whole bean coffee}', 'beverages', 'g', null, 340, 'g', null),
  ('tea bags', '{tea}', 'beverages', 'each', null, 20, 'each', null),
  ('sparkling water', '{club soda,seltzer}', 'beverages', 'ml', 1.0, 1000, 'ml', null),
  ('chicken bouillon', '{chicken bouillon cubes,chicken stock cubes}', 'pantry', 'each', null, 8, 'each', null),
  ('beef bouillon', '{beef bouillon cubes}', 'pantry', 'each', null, 8, 'each', null),
  ('beef stock', '{}', 'canned', 'ml', 1.0, 946, 'ml', null),
  ('chicken stock', '{}', 'canned', 'ml', 1.0, 946, 'ml', null),
  ('beer', '{}', 'beverages', 'ml', 1.0, 355, 'ml', null),
  ('cooking sherry', '{dry sherry}', 'beverages', 'ml', 0.99, 750, 'ml', null),
  ('marsala wine', '{marsala}', 'beverages', 'ml', 0.99, 750, 'ml', null),
  ('coconut water', '{}', 'beverages', 'ml', 1.0, 1000, 'ml', null),
  ('tomato juice', '{}', 'beverages', 'ml', 1.02, 1360, 'ml', null),
  ('apple cider', '{cider}', 'beverages', 'ml', 1.04, 1890, 'ml', null);
